In [3]:
import csv
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.io as pio

# set default
pio.templates.default = "plotly_dark"

In [4]:
# read data
df = pd.read_csv('All_States_GE.csv')
df

C:\Users\Rahul\AppData\Local\Temp\ipykernel_8592\3141721437.py:2: DtypeWarning: Columns (17,36,37,38,39,40,41,42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('All_States_GE.csv')

,State_Name,Assembly_No,Constituency_No,Year,month,Poll_No,DelimID,Position,Candidate,Sex,...,No_Terms,Turncoat,Incumbent,Recontest,MyNeta_education,TCPD_Prof_Main,TCPD_Prof_Main_Desc,TCPD_Prof_Second,TCPD_Prof_Second_Desc,Election_Type
0,Andaman_&_Nicobar_Islands,17,1,2019,4.0,0,4,1,KULDEEP RAI SHARMA,M,...,1.0,False,False,True,Graduate Professional,Business,NaN,Social Work,NaN,Lok Sabha Election (GE)
1,Andaman_&_Nicobar_Islands,17,1,2019,4.0,0,4,2,VISHAL JOLLY,M,...,0.0,False,False,False,Graduate Professional,Liberal Profession or Professional,Lawyer,NaN,NaN,Lok Sabha Election (GE)
2,Andaman_&_Nicobar_Islands,17,1,2019,4.0,0,4,3,PARITOSH KUMAR HALDAR,M,...,0.0,False,False,False,Post Graduate,Agriculture,NaN,NaN,NaN,Lok Sabha Election (GE)
3,Andaman_&_Nicobar_Islands,17,1,2019,4.0,0,4,4,SANJAY MESHACK,M,...,0.0,False,False,True,12th Pass,Business,NaN,Politics,Municipality Member,Lok Sabha Election (GE)
4,Andaman_&_Nicobar_Islands,17,1,2019,4.0,0,4,5,PRAKASH MINJ,M,...,0.0,False,False,False,Post Graduate,Social Work,NaN,NaN,NaN,Lok Sabha Election (GE)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91664,Mysore,3,23,1965,NaN,1,1,3,S.P.N.S.GAWDA,NaN,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,Lok Sabha Election (GE)
91665,Uttar_Pradesh,3,76,1965,NaN,1,1,1,N.DEO,M,...,1.0,False,False,False,NaN,NaN,NaN,NaN,NaN,Lok Sabha Election (GE)
91666,Uttar_Pradesh,3,76,1965,NaN,1,1,2,R.S.NIM,NaN,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,Lok Sabha Election (GE)
91667,Uttar_Pradesh,3,76,1965,NaN,1,1,3,R.SINGH,NaN,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,Lok Sabha Election (GE)
91668,Uttar_Pradesh,3,76,1965,NaN,1,1,4,G.DEVI,NaN,...,0.0,False,False,False,NaN,NaN,NaN,NaN,NaN,Lok Sabha Election (GE)

In [5]:
# Unique Education Bars
ed = [x for x in list(df["MyNeta_education"]) if str(x) != 'nan']
# count
ed_count = {}
for i in ed:
    if i in ed_count:
        ed_count[i] += 1
    else:
        ed_count[i] = 1

# sort
ed_count = {k: v for k, v in sorted(ed_count.items(), key=lambda item: item[1], reverse=True)}
ed_count

{'Graduate': 5056,
 'Post Graduate': 4389,
 '10th Pass': 3802,
 '12th Pass': 3515,
 'Graduate Professional': 2553,
 '8th Pass': 1968,
 'Literate': 1128,
 '5th Pass': 1067,
 'Others': 677,
 'Doctorate': 645,
 'Illiterate': 322}

In [6]:
# Education Map according to documentation
ed_map = {
    "Others": 0,
    "Illiterate": 1,
    "Literate": 2,
    "5th Pass": 3,
    "8th Pass": 4,
    "10th Pass": 5,
    "12th Pass": 6,
    "Graduate": 7,
    "Graduate Professional": 8,
    "Post Graduate": 9,
    "Doctorate": 10
}

stateVals = {}
# iterate through rows
for i in range(len(df)):
    # get education
    row = df.loc[i]
    stateName = row["State_Name"]
    ed = row["MyNeta_education"]
    # check if nan
    if str(ed) == 'nan':
        continue

    # get education value
    edVal = ed_map[ed]
    # check if state exists
    if stateName in stateVals:
        stateVals[stateName].append(edVal)
    else:
        stateVals[stateName] = [edVal]

# sort based on mean
stateVals = {k: v for k, v in sorted(stateVals.items(), key=lambda item: np.mean(item[1]), reverse=True)}

means = {}
for state in stateVals:
    print(f"State: {state}")
    # Mean std dev
    means[state] = np.mean(stateVals[state])
    print(f"Mean: {means[state] }")
    print(f"Std Dev: {np.std(stateVals[state])}")
    
    print()

State: Nagaland
Mean: 7.666666666666667
Std Dev: 1.0274023338281626

State: Manipur
Mean: 7.655172413793103
Std Dev: 1.9524672643989056

State: Mizoram
Mean: 7.428571428571429
Std Dev: 2.258769757263128

State: Sikkim
Mean: 7.321428571428571
Std Dev: 1.8526731927632767

State: Lakshadweep
Mean: 7.3
Std Dev: 1.705872210923198

State: Meghalaya
Mean: 7.25
Std Dev: 2.03100960115899

State: Odisha
Mean: 6.958974358974359
Std Dev: 1.9711662497003957

State: Goa
Mean: 6.904761904761905
Std Dev: 2.1135562877306806

State: Arunachal_Pradesh
Mean: 6.886363636363637
Std Dev: 1.4956893985248088

State: Assam
Mean: 6.694244604316546
Std Dev: 2.00539810304077

State: Uttarakhand
Mean: 6.673076923076923
Std Dev: 2.3140137776844827

State: Himachal_Pradesh
Mean: 6.6
Std Dev: 2.4232209969377534

State: West_Bengal
Mean: 6.5372374283895605
Std Dev: 2.202159060117895

State: Andhra_Pradesh
Mean: 6.525401069518717
Std Dev: 2.4127882830941236

State: Uttar_Pradesh
Mean: 6.411829436038515
Std Dev: 2.325653320183594

State: Tripura
Mean: 6.36
Std Dev: 2.3530972497257028

State: Delhi
Mean: 6.349802371541502
Std Dev: 2.1637897603396907

State: Jharkhand
Mean: 6.345201238390093
Std Dev: 2.0269164473604997

State: Chandigarh
Mean: 6.317073170731708
Std Dev: 2.331533823528151

State: Andaman_&_Nicobar_Islands
Mean: 6.26530612244898
Std Dev: 2.1454794450532937

State: Jammu_&_Kashmir
Mean: 6.256140350877193
Std Dev: 2.1637376323633

State: Karnataka
Mean: 6.242268041237113
Std Dev: 2.1564872527574996

State: Haryana
Mean: 6.226736566186108
Std Dev: 2.217461554527106

State: Bihar
Mean: 6.186206896551724
Std Dev: 2.3214726010990496

State: Kerala
Mean: 6.141043723554302
Std Dev: 2.314453155701347

State: Madhya_Pradesh
Mean: 6.079937304075235
Std Dev: 2.3327850071290643

State: Chhattisgarh
Mean: 6.072595281306715
Std Dev: 2.3283528948183414

State: Tamil_Nadu
Mean: 5.983599482088908
Std Dev: 2.480426333340978

State: Puducherry
Mean: 5.963636363636364
Std Dev: 2.743346571839428

State: Rajasthan
Mean: 5.9482029598308666
Std Dev: 2.347339356816328

State: Maharashtra
Mean: 5.922714078374455
Std Dev: 2.3312835948928035

State: Telangana
Mean: 5.731428571428571
Std Dev: 2.558322154244449

State: Punjab
Mean: 5.541443850267379
Std Dev: 2.311247562459623

State: Dadra_&_Nagar_Haveli
Mean: 5.354838709677419
Std Dev: 1.6372358116709056

State: Gujarat
Mean: 5.2418367346938775
Std Dev: 2.293220864314668

State: Daman_&_Diu
Mean: 4.588235294117647
Std Dev: 2.3778097566362044

In [14]:
# INDIA State value\n
stateMin = min(means, key=means.get)
stateMax = max(means, key=means.get)
for state in stateVals:
    stateVal = means[state]
    # scale from 0 to 100
    stateVal = (stateVal - means[stateMin]) / (means[stateMax] - means[stateMin]) * 100


    print(f"INDIA\t{state.upper().replace('_', ' ')}\t{stateVal}")

INDIA	NAGALAND	100.0
INDIA	MANIPUR	99.62661981111354
INDIA	MIZORAM	92.26569608735214
INDIA	SIKKIM	88.78525932666058
INDIA	LAKSHADWEEP	88.08917197452229
INDIA	MEGHALAYA	86.46496815286623
INDIA	ODISHA	77.01126898579128
INDIA	GOA	75.25022747952684
INDIA	ARUNACHAL PRADESH	74.65257672264042
INDIA	ASSAM	68.41176740136552
INDIA	UTTARAKHAND	67.72415482606566
INDIA	HIMACHAL PRADESH	65.35031847133756
INDIA	WEST BENGAL	63.31153429800482
INDIA	ANDHRA PRADESH	62.92704111175449
INDIA	UTTAR PRADESH	59.2377714891492
INDIA	TRIPURA	57.55414012738854
INDIA	DELHI	57.222879585106114
INDIA	JHARKHAND	57.07341602413677
INDIA	CHANDIGARH	56.159701724405785
INDIA	ANDAMAN & NICOBAR ISLANDS	54.478096971272585
INDIA	JAMMU & KASHMIR	54.180355346966145
INDIA	KARNATAKA	53.729726180313875
INDIA	HARYANA	53.22520055763788
INDIA	BIHAR	51.90863167142542
INDIA	KERALA	50.44154770781489
INDIA	MADHYA PRADESH	48.45656210690255
INDIA	CHHATTISGARH	48.21806327811623
INDIA	TAMIL NADU	45.32711693409829
INDIA	PUDUCHERRY	44.67863346844239
INDIA	RAJASTHAN	44.1772935996014
INDIA	MAHARASHTRA	43.34931082617658
INDIA	TELANGANA	37.13557779799818
INDIA	PUNJAB	30.964099594672835
INDIA	DADRA & NAGAR HAVELI	24.902403944935273
INDIA	GUJARAT	21.23163915247628
INDIA	DAMAN & DIU	0.0

In [19]:
binaryVals = {}
for state in stateVals:
    binaryVals[state] = []
    for val in stateVals[state]:
        if val <= 1:
            binaryVals[state].append(0)
        else:
            binaryVals[state].append(1)

binaryMeans = {}
for state in binaryVals:
    binaryMeans[state] = np.mean(binaryVals[state])

binaryMin = min(binaryMeans, key=binaryMeans.get)
binaryMax = max(binaryMeans, key=binaryMeans.get)

for state in binaryVals:
    stateVal = binaryMeans[state]
    # scale from 0 to 100
    stateVal = (stateVal - binaryMeans[binaryMin]) / (binaryMeans[binaryMax] - binaryMeans[binaryMin]) * 100

    print(f"INDIA\t{state.upper().replace('_', ' ')}\t{stateVal}")

INDIA	NAGALAND	100.0
INDIA	MANIPUR	80.45977011494256
INDIA	MIZORAM	59.52380952380955
INDIA	SIKKIM	100.0
INDIA	LAKSHADWEEP	100.0
INDIA	MEGHALAYA	82.29166666666667
INDIA	ODISHA	84.5014245014245
INDIA	GOA	73.01587301587298
INDIA	ARUNACHAL PRADESH	100.0
INDIA	ASSAM	90.82733812949641
INDIA	UTTARAKHAND	78.20512820512823
INDIA	HIMACHAL PRADESH	68.26666666666664
INDIA	WEST BENGAL	75.47209845109272
INDIA	ANDHRA PRADESH	64.7727272727273
INDIA	UTTAR PRADESH	83.63136176066023
INDIA	TRIPURA	69.77777777777779
INDIA	DELHI	80.96179183135703
INDIA	JHARKHAND	89.47368421052633
INDIA	CHANDIGARH	65.44715447154469
INDIA	ANDAMAN & NICOBAR ISLANDS	88.43537414965985
INDIA	JAMMU & KASHMIR	80.11695906432749
INDIA	KARNATAKA	79.13598429062348
INDIA	HARYANA	81.43294014853646
INDIA	BIHAR	81.50191570881228
INDIA	KERALA	72.82557592853783
INDIA	MADHYA PRADESH	83.56844305120167
INDIA	CHHATTISGARH	75.31760435571688
INDIA	TAMIL NADU	64.04833836858005
INDIA	PUDUCHERRY	58.787878787878775
INDIA	RAJASTHAN	88.61874559548978
INDIA	MAHARASHTRA	79.43880019351717
INDIA	TELANGANA	32.000000000000014
INDIA	PUNJAB	60.60606060606064
INDIA	DADRA & NAGAR HAVELI	81.7204301075269
INDIA	GUJARAT	83.80952380952381
INDIA	DAMAN & DIU	0.0